
"""Initial migration

Revision ID: b9d55ce1366e
Revises: 
Create Date: 2026-02-11 00:08:06.108769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d55ce1366e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('camera_devices',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('camera_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('connection_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_index(op.f('ix_camera_devices_camera_id'), 'camera_devices', ['camera_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('face_profiles',
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('embedding_ref', sa.String(), nullable=False),
    sa.Column('avg_match_score', sa.Float(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('face_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_face_profiles_face_id'), 'face_profiles', ['face_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_devices.camera_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_created_by'), 'sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_sessions_org_id'), 'sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_system_logs_log_id'), 'system_logs', ['log_id'], unique=False)
    op.create_table('adaptive_thresholds',
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('face_threshold', sa.Float(), nullable=True),
    sa.Column('liveness_threshold', sa.Float(), nullable=True),
    sa.Column('engagement_threshold', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.create_index(op.f('ix_adaptive_thresholds_threshold_id'), 'adaptive_thresholds', ['threshold_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(length=20), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_id'), 'attendance_records', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('environment_metrics',
    sa.Column('env_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('lighting_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('env_id')
    )
    op.create_index(op.f('ix_environment_metrics_env_id'), 'environment_metrics', ['env_id'], unique=False)
    op.create_table('ai_decision_logs',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.attendance_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_ai_decision_logs_decision_id'), 'ai_decision_logs', ['decision_id'], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('head_pose_score', sa.Float(), nullable=True),
    sa.Column('eye_gaze_score', sa.Float(), nullable=True),
    sa.Column('engagement_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.attendance_id'], ),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    op.create_index(op.f('ix_engagement_metrics_engagement_id'), 'engagement_metrics', ['engagement_id'], unique=False)
    op.create_table('fraud_analysis',
    sa.Column('fraud_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('fraud_reason', sa.String(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.attendance_id'], ),
    sa.PrimaryKeyConstraint('fraud_id')
    )
    op.create_index(op.f('ix_fraud_analysis_fraud_id'), 'fraud_analysis', ['fraud_id'], unique=False)
    op.create_table('presence_logs',
    sa.Column('presence_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('presence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.attendance_id'], ),
    sa.PrimaryKeyConstraint('presence_id')
    )
    op.create_index(op.f('ix_presence_logs_presence_id'), 'presence_logs', ['presence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presence_logs_presence_id'), table_name='presence_logs')
    op.drop_table('presence_logs')
    op.drop_index(op.f('ix_fraud_analysis_fraud_id'), table_name='fraud_analysis')
    op.drop_table('fraud_analysis')
    op.drop_index(op.f('ix_engagement_metrics_engagement_id'), table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index(op.f('ix_ai_decision_logs_decision_id'), table_name='ai_decision_logs')
    op.drop_table('ai_decision_logs')
    op.drop_index(op.f('ix_environment_metrics_env_id'), table_name='environment_metrics')
    op.drop_table('environment_metrics')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_adaptive_thresholds_threshold_id'), table_name='adaptive_thresholds')
    op.drop_table('adaptive_thresholds')
    op.drop_index(op.f('ix_system_logs_log_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_org_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_by'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_face_profiles_face_id'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_camera_devices_camera_id'), table_name='camera_devices')
    op.drop_table('camera_devices')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
