
"""Add class_type to Session

Revision ID: 4ce95c594116
Revises: 7cbbefbd12b9
Create Date: 2026-05-27 15:01:44.865988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce95c594116'
down_revision: Union[str, None] = '7cbbefbd12b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_devices_org_id_fkey', 'camera_devices', type_='foreignkey')
    op.create_foreign_key(None, 'camera_devices', 'organizations', ['org_id'], ['org_id'])
    op.add_column('sessions', sa.Column('class_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'class_type')
    op.drop_constraint(None, 'camera_devices', type_='foreignkey')
    op.create_foreign_key('camera_devices_org_id_fkey', 'camera_devices', 'organizations', ['org_id'], ['org_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
