
"""add_image_url

Revision ID: 7cbbefbd12b9
Revises: f7fc5e4d4e29
Create Date: 2026-02-27 18:06:53.560954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbbefbd12b9'
down_revision: Union[str, None] = 'f7fc5e4d4e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_profiles', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_profiles', 'image_url')
    # ### end Alembic commands ###
