
"""Add org_id to attendance records

Revision ID: ed64eb292a34
Revises: aa66b81e7053
Create Date: 2026-05-28 17:44:35.260097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed64eb292a34'
down_revision: Union[str, None] = 'aa66b81e7053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendance_records_org_id'), 'attendance_records', ['org_id'], unique=False)
    op.create_foreign_key(None, 'attendance_records', 'organizations', ['org_id'], ['org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_records_org_id'), table_name='attendance_records')
    op.drop_column('attendance_records', 'org_id')
    # ### end Alembic commands ###
