
"""Add pgvector and modify FaceProfile

Revision ID: f7fc5e4d4e29
Revises: b9d55ce1366e
Create Date: 2026-02-24 23:05:13.970379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f7fc5e4d4e29'
down_revision: Union[str, None] = 'b9d55ce1366e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.add_column('face_profiles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False))
    op.drop_column('face_profiles', 'embedding_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.add_column('face_profiles', sa.Column('embedding_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('face_profiles', 'embedding')
    # ### end Alembic commands ###
